.TH SBAR 1 SBAR
.SH NAME
sbar \- status bar for dwm
.SH SYNOPSIS
.B sbar
.RB [\-d\]\ [\-h]\ [\-o]\ [\-v]
.SH DESCRIPTION
slstatus is a suckless and lightweight status monitor for window managers that use WM_NAME as statusbar (e.g. DWM) or any other status bars as long as they support reading from stdin. It is written in pure C without any extern programs being executed and only reads from files most of the time. slstatus is meant to be a better alternative to Bash scripts (inefficient) and Conky (bloated and written in C++).
.SH OPTIONS
.TP
.B \-d
daemonize
.TP
.B \-h
display usage
.TP
.B \-o
write to stdout instead of dwm status bar
.TP
.B \-v
version
.SH CONFIGURATION
See config.def.h
.SH AUTHORS
Aaron Marcher (drkhsh).
Ali H. Fardan (Raiz).
.SH LICENSE
ISC
.SH BUGS
probably
