.TH SBAR 1 SBAR
.SH NAME
sbar \- status bar for dwm
.SH SYNOPSIS
.B sbar
.RB [\-d\]\ [\-h]\ [\-o]\ [\-v]
.SH DESCRIPTION
.B sbar
is a fork of slstatus with Linux dependencies removed and some small rewrites.
.SH OPTIONS
.TP
.B \-d
daemonize
.TP
.B \-h
display usage
.TP
.B \-o
write to stdout instead of dwm status bar
.TP
.B \-v
version
.SH CONFIGURATION
See config.def.h
.SH AUTHORS
Aaron Marcher (drkhsh).
Ali H. Fardan (Raiz).
.SH LICENSE
ISC
.SH BUGS
probably
